"""QES — Quantum Evolutionary Space.

A general-purpose, domain-agnostic framework for governed possibility-space
computation: a dynamically generated computational space in which
alternative states, equations, configurations, and trajectories are
instantiated as isolated virtual realities ("rooms"), executed in parallel,
constrained by permission laws, tested for divergence and collapse,
recursively evolved, and compressed toward validated surviving solutions.

QES is not tied to any single domain (finance, engineering, physics,
control, etc.) — it provides the reusable primitives (rooms, state spaces,
divergence measures, permission kernels, selection, compute allocation,
orchestration) needed to build governed exploration/optimization systems
for any domain that can be expressed as a bounded state space with an
admissibility criterion.

QES itself is the digital universe those primitives operate inside of, not
merely a computation: `Universe` (`Q = {S, E, A, R, M, C, T, G}`) hosts
`World`s (virtual realities/environments) which in turn host room
populations (`QESSpace`), intelligent `Agent`s, and optionally further
nested universes, giving the recursive containment chain
`Q^(0) supseteq Q^(1) supseteq ...`.

See docs/QES-architecture.md for the full formal specification this
framework implements.
"""

from qes.adversarial import (
    AdversarialCandidate,
    AdversarialGenerator,
    FailureAnalysis,
    FailureCategory,
    RedTeamReport,
    run_red_team_campaign,
)
from qes.agent import Agent, Message
from qes.backend import (
    BackendError,
    BackendRegistry,
    BackendUnavailableError,
    BenchmarkResult,
    ComputeBackend,
    GPUBackend,
    NumpyBackend,
    UnknownBackendError,
    benchmark_backend,
    get_backend,
)
from qes.bench import (
    BaselineResult,
    BenchmarkMetrics,
    BenchmarkProblem,
    BenchReport,
    make_rastrigin_problem,
    make_rosenbrock_problem,
    make_sphere_problem,
    run_bayesian_optimization_baseline,
    run_cma_es_baseline,
    run_differential_evolution_baseline,
    run_evolutionary_algorithm_baseline,
    run_genetic_algorithm_baseline,
    run_gradient_method_baseline,
    run_mpc_baseline,
    run_multi_objective_baseline,
    run_qes_baseline,
    run_qes_bench,
    run_reinforcement_learning_baseline,
    run_simulated_annealing_baseline,
    run_symbolic_regression_baseline,
)
from qes.causal_engine import (
    CausalDiscoveryResult,
    CausalEdge,
    CausalGraph,
    CounterfactualResult,
    HiddenVariableHypothesis,
    InterventionResult,
    SensitivityResult,
    analyze_causality,
    counterfactual,
    hidden_variable_hypotheses,
    intervene,
    perturbation_sensitivity,
)
from qes.closure import (
    CrossDomainVerifier,
    DomainVerificationResult,
    PermissionClosure,
    PermissionClosureResult,
    action_selection,
    collapse_proximity,
    divergence,
    divergence_gradient,
    safe_exploration_closure,
)
from qes.communication import (
    MESSAGE_KINDS,
    Coalition,
    CommunicationFabric,
    ResourceBid,
    ResourceNegotiation,
    compete,
    cooperate,
    form_coalition,
)
from qes.communication import (
    Message as CommunicationMessage,
)
from qes.compute_allocator import ComputeAllocator
from qes.convergence import convergence_coefficient, gini_coefficient, kl_divergence, qes_entropy
from qes.cycle import AutonomousCycle, CycleHistory, GenerationReport, adaptive_branch_count
from qes.digital_twin import DigitalTwin
from qes.digital_twin_loop import (
    AnomalyReport,
    DigitalTwinLoop,
    DriftReport,
    LoopStepResult,
    ModelSelectionResult,
    ModelSelector,
    Observation,
    OnlineParameterEstimator,
    PropagationResult,
    StateEstimator,
    anomaly_detection,
    calibration_check,
    drift_detection,
    prediction_interval,
    sensor_fusion,
    uncertainty_propagation,
)
from qes.distributed import (
    Controller,
    Worker,
    WorkItem,
    autoscaling_policy,
    distributed_checkpoint,
    restore_from_checkpoint,
)
from qes.divergence import DSA, DivergenceResult, hsa_state
from qes.domain import DomainNullification
from qes.domain_packs import (
    ControlPolicyPack,
    ControlPolicyPackConfig,
    ControlPolicyPackResult,
    DesignSpacePack,
    DesignSpacePackConfig,
    DesignSpacePackResult,
    DomainPackDescriptor,
    DomainPackRegistry,
    ResourceAllocationPack,
    ResourceAllocationPackConfig,
    ResourceAllocationPackResult,
    ResourceJob,
    list_domain_packs,
    make_control_policy_space,
    make_design_space,
    make_resource_allocation_pack,
)
from qes.equation_ast import (
    Constant,
    DimensionValidation,
    EquationAST,
    EquationASTEvolutionResult,
    EquationASTForge,
    EvolutionSnapshot,
    NumericalValidation,
    Operator,
    Primitive,
    StabilityReport,
    Variable,
    primitive_library,
    replace_subtree,
    simplify_ast,
    subtree_at,
)
from qes.equation_forge import Equation, EquationForge
from qes.events import (
    EVENT_KINDS,
    DeterministicReplay,
    Event,
    EventLog,
    LineageGraph,
    ReplayMismatch,
    ReplayReport,
    state_hash,
)
from qes.execution import ExecutionBudget, ExecutionStopped
from qes.expansion import DomainBirthKernel, InfinityRouter, MetaExpansionEngine
from qes.gpu_compute import (
    GPUCapabilityReport,
    GPUComputeBackend,
    GPUComputeUnavailableError,
    PopulationConvergenceResult,
    PopulationDivergenceResult,
    SimulatedGPUBackend,
    is_gpu_runtime_available,
    probe_gpu_runtime,
)
from qes.h11x import (
    H11X,
    CorrectionOutcome,
    ExportResult,
    Geometry,
    H11XResult,
    constraint_geometry,
    domain_gatekeeper,
    export_barrier,
    failure_anticipation,
    necessity_field,
    self_generative_correction,
)
from qes.hypervisor import CosmicVP, RequestCycleResult, VirtualResource
from qes.information_gain import (
    InformationGainEstimator,
    allocate_by_information_gain,
    information_gain,
    population_entropy,
    rank_by_information_gain,
)
from qes.intelligence import (
    AdaptiveGradientSearch,
    AdaptiveSearchConfig,
    NoFeasibleSolutionError,
    OptimizationResult,
    optimize,
)
from qes.invariants import InvariantEngine, InvariantReport, InvariantViolation
from qes.kernel import (
    ComputableGeometry,
    ConstructionResult,
    DomainGenerationResult,
    ExistenceKernel,
    OperationResult,
    PersistenceResult,
    RealitySelectionResult,
    RealitySelector,
    RecursiveEntity,
    RecursiveEntityResult,
    RejectionError,
    SelfGeneratingDomainIntelligence,
)
from qes.knowledge_graph import (
    NODE_KINDS,
    CausalHypothesis,
    KnowledgeGraph,
    KnowledgeNode,
)
from qes.marketplace import (
    MarketBid,
    RealityAccount,
    RealityMarketplace,
    compute_allocation_score,
)
from qes.meta_learning import (
    MetaController,
    ProblemStructure,
    SearchHistory,
    SearchOutcome,
    SearchStrategy,
    record_outcome,
)
from qes.metrics import (
    aggregate_weights_stats,
    average_gate_fidelity,
    fidelity,
    layer_norms,
    pure_state_distance,
    purity,
    state_overlap,
)
from qes.multi_agent import AutonomousNodeRouter, CognitiveAgentSpawner, LayeredRoleEngine
from qes.multi_agent_evolution import (
    SPECIALIZATIONS,
    AgentPerformanceRecord,
    AgentPopulation,
    CollectiveSolutionResult,
    ComparisonResult,
    ScoredCandidate,
    SharedInsight,
    SpecializedAgent,
    collective_solution,
    compare_individual_vs_collective,
)
from qes.multi_agent_evolution import (
    Coalition as SpecialistCoalition,
)
from qes.multi_reality import (
    VQCE,
    PatternReplicationLayer,
    SimulationEngine,
    VirtualNodeProjection,
)
from qes.observatory import (
    ObservatoryDashboard,
    ObservatorySnapshot,
    build_snapshot_from_modules,
    render_reality_tree,
)
from qes.orchestrator import Acros, AdaptiveAcros, RoomLifecycle
from qes.parallel_fabric import (
    ErrorCorrectionDomain,
    ExecutionDomain,
    MonitoringDomain,
    ParallelComputeDomain,
    PredictionDomain,
    SynchronizationDomain,
)
from qes.patterns import PatternMemory
from qes.permission import AdaptivePermission, GenesisPermission, PermissionResult
from qes.qsee import BIG11, QEL, QSEE11L, AcrosV12BIESync, SyncResult
from qes.real_distributed import (
    Coordinator as RealDistributedCoordinator,
)
from qes.real_distributed import (
    TaskExecutionResult as RealDistributedTaskResult,
)
from qes.real_distributed import (
    TaskServer as RealDistributedTaskServer,
)
from qes.real_distributed import (
    WorkerProcess as RealDistributedWorkerProcess,
)
from qes.reality_generator import RealityGenerator
from qes.reality_operators import (
    RealityFamily,
    RealityFamilyBuilder,
    crossover,
    dimensional_transformation,
    equation_substitution,
    extrapolate,
    interpolate,
    inversion,
    mutation,
    parameter_transformation,
    perturbation,
    topology_transformation,
)
from qes.reproducibility import (
    ExperimentArtifact,
    ExperimentRecorder,
    ReproductionCheckResult,
    load_artifact,
    reproduce_experiment,
    save_artifact,
    verify_reproduction,
)
from qes.room import Room
from qes.rpc_fault_tolerance import (
    FailureDetector,
    LeaderElection,
    RetryPolicy,
    RPCClient,
    RPCConnectionError,
    RPCError,
    RPCRemoteError,
    RPCServer,
)
from qes.runtime import (
    ApiKeyGuard,
    DistributedRuntime,
    FileRuntimeStore,
    PostgresRuntimeStore,
    ProductionRuntime,
    RedisRuntimeStore,
    RuntimeAccessError,
    RuntimeJob,
    RuntimeScheduler,
    RuntimeStore,
    SQLiteRuntimeStore,
)
from qes.sdk import (
    QESClient,
    SDKPermissionConfig,
    SDKRunResult,
    quick_search,
)
from qes.security import (
    AccessControlList,
    AuthToken,
    InvalidTokenError,
    PermissionDeniedError,
    QuotaExceededError,
    QuotaManager,
    ResourceQuota,
    SandboxPolicy,
    SandboxViolationError,
    SecurityError,
    TokenExpiredError,
    TokenIssuer,
)
from qes.security import (
    Permission as SecurityPermission,
)
from qes.security import (
    Role as SecurityRole,
)
from qes.selection import (
    GenesisSelection,
    GenesisSelectionPipeline,
    KindTrace,
    PipelineResult,
    pareto_front,
)
from qes.self_improvement import (
    ApprovalPolicy,
    ArchitectureProposal,
    PerformanceEvaluation,
    ProposalEvaluation,
    RegressionTestResult,
    SafetyTestResult,
    Sandbox,
    SelfImprovementPipeline,
    SelfImprovementReport,
    default_approval_policy,
    propose_alternatives,
    run_in_sandbox,
    run_regression_tests,
    run_safety_tests,
)
from qes.self_improvement import (
    BenchmarkResult as SelfImprovementBenchmarkResult,
)
from qes.space import QESSpace
from qes.state_space import MCCStateSpace
from qes.storage_backend import (
    CheckpointStore,
    LocalFilesystemStorageBackend,
    S3StorageBackend,
    StorageBackend,
)
from qes.task_queue import RegisteredTaskWorker, SQLiteTaskQueue, StaleLeaseError, TaskLease
from qes.universe import Universe, UniverseComparison, UniverseTelemetry
from qes.validation import (
    FailureRecoveryLoop,
    FunctionalSafetySystem,
    IntegrityValidator,
    ValidationFramework,
)
from qes.verification import (
    Evidence,
    VerificationEngine,
    VerificationStageResult,
    constraint_verification,
    cross_domain_verification,
    invariant_verification,
    numerical_verification,
    safety_verification,
    stability_verification,
)
from qes.world import World
from qes.x_engine import AcrosV12BIE, AcrosV13, ApexI, GeoM, XEnginePipelineResult, x_engine_pipeline

__all__ = [
    "ExecutionBudget",
    "ExecutionStopped",
    "NoFeasibleSolutionError",
    "RegisteredTaskWorker",
    "SQLiteTaskQueue",
    "StaleLeaseError",
    "TaskLease",
    "Room",
    "MCCStateSpace",
    "DomainNullification",
    "DSA",
    "DivergenceResult",
    "hsa_state",
    "GenesisPermission",
    "AdaptivePermission",
    "PermissionResult",
    "Equation",
    "EquationForge",
    "RealityGenerator",
    "RealityFamily",
    "RealityFamilyBuilder",
    "mutation",
    "crossover",
    "interpolate",
    "extrapolate",
    "inversion",
    "perturbation",
    "dimensional_transformation",
    "topology_transformation",
    "equation_substitution",
    "parameter_transformation",
    "BackendError",
    "BackendRegistry",
    "BackendUnavailableError",
    "BenchmarkResult",
    "ComputeBackend",
    "GPUBackend",
    "NumpyBackend",
    "UnknownBackendError",
    "benchmark_backend",
    "get_backend",
    "CausalDiscoveryResult",
    "CausalEdge",
    "CausalGraph",
    "CounterfactualResult",
    "HiddenVariableHypothesis",
    "InterventionResult",
    "SensitivityResult",
    "analyze_causality",
    "counterfactual",
    "hidden_variable_hypotheses",
    "intervene",
    "perturbation_sensitivity",
    "MarketBid",
    "RealityAccount",
    "RealityMarketplace",
    "compute_allocation_score",
    "AdaptiveGradientSearch",
    "AdaptiveSearchConfig",
    "OptimizationResult",
    "optimize",
    "GenesisSelection",
    "pareto_front",
    "ComputeAllocator",
    "MESSAGE_KINDS",
    "CommunicationMessage",
    "CommunicationFabric",
    "ResourceBid",
    "ResourceNegotiation",
    "Coalition",
    "compete",
    "cooperate",
    "form_coalition",
    "Constant",
    "DimensionValidation",
    "EquationAST",
    "EquationASTEvolutionResult",
    "EquationASTForge",
    "EvolutionSnapshot",
    "NumericalValidation",
    "Operator",
    "Primitive",
    "StabilityReport",
    "Variable",
    "primitive_library",
    "replace_subtree",
    "simplify_ast",
    "subtree_at",
    "information_gain",
    "population_entropy",
    "InformationGainEstimator",
    "rank_by_information_gain",
    "allocate_by_information_gain",
    "NODE_KINDS",
    "CausalHypothesis",
    "KnowledgeGraph",
    "KnowledgeNode",
    "DigitalTwin",
    "qes_entropy",
    "convergence_coefficient",
    "kl_divergence",
    "gini_coefficient",
    "Acros",
    "AdaptiveAcros",
    "RoomLifecycle",
    "PatternMemory",
    "QESSpace",
    "Agent",
    "Message",
    "World",
    "Universe",
    "UniverseTelemetry",
    "UniverseComparison",
    "CosmicVP",
    "VirtualResource",
    "RequestCycleResult",
    "AcrosV12BIE",
    "AcrosV13",
    "ApexI",
    "GeoM",
    "XEnginePipelineResult",
    "x_engine_pipeline",
    "ParallelComputeDomain",
    "SynchronizationDomain",
    "PredictionDomain",
    "ExecutionDomain",
    "MonitoringDomain",
    "ErrorCorrectionDomain",
    "SimulationEngine",
    "VirtualNodeProjection",
    "PatternReplicationLayer",
    "VQCE",
    "ValidationFramework",
    "FunctionalSafetySystem",
    "FailureRecoveryLoop",
    "IntegrityValidator",
    "DomainBirthKernel",
    "InfinityRouter",
    "MetaExpansionEngine",
    "CognitiveAgentSpawner",
    "LayeredRoleEngine",
    "AutonomousNodeRouter",
    "QEL",
    "BIG11",
    "AcrosV12BIESync",
    "SyncResult",
    "QSEE11L",
    "necessity_field",
    "Geometry",
    "constraint_geometry",
    "domain_gatekeeper",
    "failure_anticipation",
    "CorrectionOutcome",
    "self_generative_correction",
    "ExportResult",
    "export_barrier",
    "H11XResult",
    "H11X",
    "divergence",
    "divergence_gradient",
    "collapse_proximity",
    "PermissionClosureResult",
    "PermissionClosure",
    "action_selection",
    "safe_exploration_closure",
    "DomainVerificationResult",
    "CrossDomainVerifier",
    "GenesisSelectionPipeline",
    "KindTrace",
    "PipelineResult",
    "ProductionRuntime",
    "RuntimeJob",
    "RuntimeScheduler",
    "RuntimeStore",
    "FileRuntimeStore",
    "SQLiteRuntimeStore",
    "RedisRuntimeStore",
    "PostgresRuntimeStore",
    "DistributedRuntime",
    "ApiKeyGuard",
    "RuntimeAccessError",
    "ExistenceKernel",
    "RejectionError",
    "ConstructionResult",
    "OperationResult",
    "PersistenceResult",
    "ComputableGeometry",
    "RecursiveEntity",
    "RecursiveEntityResult",
    "SelfGeneratingDomainIntelligence",
    "DomainGenerationResult",
    "RealitySelector",
    "RealitySelectionResult",
    "InvariantEngine",
    "InvariantReport",
    "InvariantViolation",
    "AutonomousCycle",
    "CycleHistory",
    "GenerationReport",
    "adaptive_branch_count",
    "EVENT_KINDS",
    "Event",
    "EventLog",
    "LineageGraph",
    "state_hash",
    "ReplayMismatch",
    "ReplayReport",
    "DeterministicReplay",
    "AdversarialCandidate",
    "AdversarialGenerator",
    "FailureAnalysis",
    "FailureCategory",
    "RedTeamReport",
    "run_red_team_campaign",
    "Observation",
    "PropagationResult",
    "ModelSelectionResult",
    "AnomalyReport",
    "DriftReport",
    "LoopStepResult",
    "sensor_fusion",
    "OnlineParameterEstimator",
    "StateEstimator",
    "uncertainty_propagation",
    "ModelSelector",
    "anomaly_detection",
    "prediction_interval",
    "calibration_check",
    "drift_detection",
    "DigitalTwinLoop",
    "Controller",
    "Worker",
    "WorkItem",
    "autoscaling_policy",
    "distributed_checkpoint",
    "restore_from_checkpoint",
    "MetaController",
    "ProblemStructure",
    "SearchHistory",
    "SearchOutcome",
    "SearchStrategy",
    "record_outcome",
    "SPECIALIZATIONS",
    "AgentPerformanceRecord",
    "AgentPopulation",
    "CollectiveSolutionResult",
    "ComparisonResult",
    "ScoredCandidate",
    "SharedInsight",
    "SpecializedAgent",
    "SpecialistCoalition",
    "collective_solution",
    "compare_individual_vs_collective",
    "ApprovalPolicy",
    "ArchitectureProposal",
    "PerformanceEvaluation",
    "ProposalEvaluation",
    "RegressionTestResult",
    "Sandbox",
    "SafetyTestResult",
    "SelfImprovementPipeline",
    "SelfImprovementReport",
    "SelfImprovementBenchmarkResult",
    "default_approval_policy",
    "propose_alternatives",
    "run_in_sandbox",
    "run_regression_tests",
    "run_safety_tests",
    "Evidence",
    "VerificationEngine",
    "VerificationStageResult",
    "constraint_verification",
    "cross_domain_verification",
    "invariant_verification",
    "numerical_verification",
    "safety_verification",
    "stability_verification",
    "BaselineResult",
    "BenchmarkMetrics",
    "BenchmarkProblem",
    "BenchReport",
    "make_rastrigin_problem",
    "make_rosenbrock_problem",
    "make_sphere_problem",
    "run_bayesian_optimization_baseline",
    "run_cma_es_baseline",
    "run_differential_evolution_baseline",
    "run_evolutionary_algorithm_baseline",
    "run_genetic_algorithm_baseline",
    "run_gradient_method_baseline",
    "run_mpc_baseline",
    "run_multi_objective_baseline",
    "run_qes_baseline",
    "run_qes_bench",
    "run_reinforcement_learning_baseline",
    "run_simulated_annealing_baseline",
    "run_symbolic_regression_baseline",
    "ObservatoryDashboard",
    "ObservatorySnapshot",
    "build_snapshot_from_modules",
    "render_reality_tree",
    "ExperimentArtifact",
    "ExperimentRecorder",
    "ReproductionCheckResult",
    "load_artifact",
    "reproduce_experiment",
    "save_artifact",
    "verify_reproduction",
    "ControlPolicyPack",
    "ControlPolicyPackConfig",
    "ControlPolicyPackResult",
    "DesignSpacePack",
    "DesignSpacePackConfig",
    "DesignSpacePackResult",
    "DomainPackDescriptor",
    "DomainPackRegistry",
    "ResourceAllocationPack",
    "ResourceAllocationPackConfig",
    "ResourceAllocationPackResult",
    "ResourceJob",
    "list_domain_packs",
    "make_control_policy_space",
    "make_design_space",
    "make_resource_allocation_pack",
    "QESClient",
    "SDKPermissionConfig",
    "SDKRunResult",
    "quick_search",
    "GPUCapabilityReport",
    "GPUComputeBackend",
    "GPUComputeUnavailableError",
    "PopulationConvergenceResult",
    "PopulationDivergenceResult",
    "SimulatedGPUBackend",
    "is_gpu_runtime_available",
    "probe_gpu_runtime",
    "RealDistributedCoordinator",
    "RealDistributedTaskResult",
    "RealDistributedTaskServer",
    "RealDistributedWorkerProcess",
    "FailureDetector",
    "LeaderElection",
    "RetryPolicy",
    "RPCClient",
    "RPCConnectionError",
    "RPCError",
    "RPCRemoteError",
    "RPCServer",
    "AccessControlList",
    "AuthToken",
    "InvalidTokenError",
    "SecurityPermission",
    "PermissionDeniedError",
    "QuotaExceededError",
    "QuotaManager",
    "ResourceQuota",
    "SecurityRole",
    "SandboxPolicy",
    "SandboxViolationError",
    "SecurityError",
    "TokenExpiredError",
    "TokenIssuer",
    "CheckpointStore",
    "LocalFilesystemStorageBackend",
    "S3StorageBackend",
    "StorageBackend",
    # Metrics exports
    "fidelity",
    "state_overlap",
    "purity",
    "pure_state_distance",
    "average_gate_fidelity",
    "layer_norms",
    "aggregate_weights_stats",
]

from qes._version import __version__ as __version__
